# Generated by Django 4.2.7 on 2023-12-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioAlumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='alumno',
            table=None,
        ),
    ]
