# Generated by Django 4.2.7 on 2023-12-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioAlumno', '0002_alter_alumno_carrera_alter_alumno_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='alumnos',
        ),
    ]
