# Generated by Django 4.2.7 on 2023-12-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularioRamos', '0003_inforamo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ramos',
            table=None,
        ),
    ]
