# Generated by Django 4.2.7 on 2023-12-11 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularioRamos', '0004_alter_ramos_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ramos',
            table='ramos',
        ),
    ]
